network:
  name: nca_head
  num_classes: '@{dataset.num_classes}'
  pretrained: True          # set 'True' to load pretrained model
  checkpoint: ./results/class_cifar10_head_nca.best.pth            # ignore if pretrained is false
  num_gpus: '@{num_gpus}'
