network:
  name: react_net
  num_classes: '@{dataset.num_classes}'
  image_size: '@{dataset.image_size}'
  pretrained: False
  checkpoint: none           # ignore if pretrained is false
  num_gpus: '@{num_gpus}'
  similarity_measure: 'cosine' # value in ['cosine', 'inner', 'euclid']

  # network used for feature extraction
  backbone:
    name: nca_head
    num_classes: '@{dataset.num_classes}'
    pretrained: True,
    device: "cuda:0"
    checkpoint: 'results/class_cifar10_head_nca.best.pth'
    num_gpus: '@{num_gpus}'
